# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

 

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm install
    - run: npm run test-smoke
    - run: npm run report-merge
    - run: npm run report-generate
    - name: npm run Upload Report Artfact
      uses: actions/upload-artifact@v2.2.3
      with:
        path: mochawesome-report
 
